language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=cakephp_test' db_database='cakephp_test' db_login='travis' db_password=''
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - php: 5.4
      env: COVERALLS=1 DEFAULT=0

  fast_finish: true

  include:
    - php: 5.4
      env: DB=pgsql db_class='Cake\Database\Driver\Postgres' db_dsn='pgsql:host=127.0.0.1;dbname=cakephp_test' db_database="cakephp_test" db_login='postgres' db_password=''

    - php: 5.4
      env: DB=sqlite db_class='Cake\Database\Driver\Sqlite' db_dsn='sqlite::memory:'

    - php: 5.4
      env: PHPCS=1 DEFAULT=0

    - php: 5.4
      env: COVERALLS=1 DEFAULT=0

    - php: 7.0
      env: PHPCS=1

    - php: 7.0
      env: COVERAGE=1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"

  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"

  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$COVERAGE' = '1' ]; then phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then bash codecov.sh; fi"


after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
  
notifications:
  email: false
